spring:
  config:
    import:
      - optional:classpath:args-dev.yaml
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB
  application:
    name: medrec
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.url}:${mysql.port}/${spring.datasource.name}
    name: medrec
    username: ${mysql.username}
    password: ${mysql.password}
  ai:
    openai: # openai
      base-url: "https://dashscope.aliyuncs.com/compatible-mode"
      api-key:  ${A_LI_YUN-API-KEY}
      chat:
        options:
          model: "qwen3-max"
      embedding:
        options:
          model: "text-embedding-v4"

  data:
    redis:
      host: ${redis.url}
      port: ${redis.port}
      password: ${redis.password}
      dataBase: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms
      timeout: 5000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: t_
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: ${internet.PORT}

minerU:
  token: "eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJqdGkiOiIxNDYwMDIzNCIsInJvbCI6IlJPTEVfUkVHSVNURVIiLCJpc3MiOiJPcGVuWExhYiIsImlhdCI6MTc3Njk0MjczMywiY2xpZW50SWQiOiJsa3pkeDU3bnZ5MjJqa3BxOXgydyIsInBob25lIjoiIiwib3BlbklkIjpudWxsLCJ1dWlkIjoiMGRkMGZlNGItMzhiZS00MDk2LWFiOTEtMTZjZmIzZWFiZTk1IiwiZW1haWwiOiIiLCJleHAiOjE3ODQ3MTg3MzN9.-JOpkMP5EAjCBXIY_SsIYfyQQA7IvnrnUNG9qFPsPTO3zYBJ7Zfm2gG-nDuq5rnTyl3vHpf360psaTSH-0Jrkg"